### ISSUE TITLE
Deploy application on neetoDeploy

### ISSUE THREAD

**Issue by sritabh** [sritabh/neeto-ui-challenge-by-sritabh#8]
Deployed at https://neetoui-challenge-by-sritabh.neetoreviewapp.net/
Can be logged in using:
Username : oliver@example.com
Password : welcome

@navaneethsdk @yedhink  Please review

**Comment by navaneethsdk** [comment]
@sritabh A few comments:
- [x] https://vimeo.com/852252456/d3e711c559
- [x] [This](https://github.com/sritabh/neeto-ui-challenge-by-sritabh/blob/61438e1233f8ab57b3e52634c382aa1b75fb1516/app/javascript/src/components/Dashboard/Notes/Item.jsx#L48C30-L48C49) name can be misinterpreted. The name says you are trying to calculate `createdAgo`. What is `createdAgo`? I believe I had already suggested a better name in one of the previous review. Please find a better name.
- [x] Please use `onDelete=handleDelete` over here. https://github.com/sritabh/neeto-ui-challenge-by-sritabh/blob/61438e1233f8ab57b3e52634c382aa1b75fb1516/app/javascript/src/components/Dashboard/Notes/index.jsx#L74
- [x] Please move this to `utils.js` and prefix the function with `build`. [Refer](https://academy.bigbinary.com/learn-react/react-best-practices/naming-conventions-in-react?searchTerms%5B0%5D=build#p-0-89). https://github.com/sritabh/neeto-ui-challenge-by-sritabh/blob/61438e1233f8ab57b3e52634c382aa1b75fb1516/app/javascript/src/components/Dashboard/Contacts/constants.js#L35C1-L41C3
- [x] Let's keep the `useEffect` at the end just before return statement. https://github.com/sritabh/neeto-ui-challenge-by-sritabh/blob/61438e1233f8ab57b3e52634c382aa1b75fb1516/app/javascript/src/components/Dashboard/Contacts/index.jsx#L42-L48
- [x] Shouldn't this be a constant? Why is it named like function? It's better you do not move it to a separate variable/const. https://github.com/sritabh/neeto-ui-challenge-by-sritabh/blob/61438e1233f8ab57b3e52634c382aa1b75fb1516/app/javascript/src/components/Dashboard/Contacts/index.jsx#L33-L35
- [x] Let's move this to utils.js. https://github.com/sritabh/neeto-ui-challenge-by-sritabh/blob/61438e1233f8ab57b3e52634c382aa1b75fb1516/app/javascript/src/components/Dashboard/Contacts/Table.jsx#L17-L24

**Comment by sritabh** [comment]
> https://vimeo.com/852252456/d3e711c559

I have made changes by using `trim()` from `yup` validation to not let blank entry.

> [This](https://github.com/sritabh/neeto-ui-challenge-by-sritabh/blob/61438e1233f8ab57b3e52634c382aa1b75fb1516/app/javascript/src/components/Dashboard/Notes/Item.jsx#L48C30-L48C49) name can be misinterpreted. The name says you are trying to calculate createdAgo. What is createdAgo? I believe I had already suggested a better name in one of the previous review. Please find a better name.

I have made changes, but I got the name earlier from  this articles [here](https://academy.bigbinary.com/learn-react/react-best-practices/miscellaneous-tips?searchTerms%5B0%5D=dayjs#how-to-extend-dayjs) which mentions the function `export const calculateCreatedAgo = date => dayjs(date).fromNow();`

> Shouldn't this be a constant? Why is it named like function? It's better you do not move it to a separate variable/const.

I have made all changes except this one, I am bit confused, from [here](https://academy.bigbinary.com/learn-react/react-best-practices/use-classnames-package-while-adding-conditional-classes), do we consider classNames as constant? value is dynamic right? Even the article doesn't say anything about that, do clear it.
Thanks

**Comment by navaneethsdk** [comment]
> I have made all changes except this one, I am bit confused, from [here](https://academy.bigbinary.com/learn-react/react-best-practices/use-classnames-package-while-adding-conditional-classes), do we consider classNames as constant? value is dynamic right? Even the article doesn't say anything about that, do clear it up.

Then you may use a function that returns the className. Currently, you have defined it as a constant and used the function naming standards.

**Comment by sritabh** [comment]
I have made the changes.
